---
- name: Setup the node
  become: yes
  hosts: all
  roles:
    - geerlingguy.docker
  vars:
    pip_install_packages:
      - name: docker
  tasks:
  - name: Add a dedicated user
    ansible.builtin.user:
      name: "{{ user }}"
    become_method: sudo
  - name: Upgrade all apt packages
    apt:
      force_apt_get: yes
      upgrade: dist
  - name: Install python docker
    apt: name=python3-docker state=latest

- name: Init a new swarm cluster with default parameters
  become: yes
  hosts: leader
  tasks:
  - name: Just checking the host
    ansible.builtin.debug:
      msg: "{{ ansible_host }}"
  - name: Start the leader
    community.docker.docker_swarm:
      state: present
      advertise_addr: "{{ ansible_host }}"
    register: docker_swarm_init_response
  - name: Check output
    ansible.builtin.debug:
      msg: "{{ docker_swarm_init_response }}"

- name: Add a worker node to the swarm cluster
  become: yes
  hosts: worker
  tasks:
  - name: Start the worker
    community.docker.docker_swarm:
      state: join
      join_token: "{{ hostvars[groups['master'][0]].master_output.swarm_facts.JoinTokens.Worker }}"
      remote_addrs: "{{ hostvars[groups['master'][0]].inventory_hostname }}"
      advertise_addr: "{{ ansible_host }}"
